server:
  port: 8081
spring:
  application:
    name: js-consumer-loans
  zipkin: #追踪
    base-url: http://116.62.167.249:6601
  sleuth:
    sampler:
      percentage: 1.0
  redis:
    cluster:
      nodes: 127.0.0.1:6381,127.0.0.1:6382,127.0.0.1:6383,127.0.0.1:6384,127.0.0.1:6385,127.0.0.1:6386
    pool:
      max-active: 10
      max-wait: -1
      max-idle: 8
      min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true
dm-spring-provider-zhanghu:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level: info