server:
  port: 8024
spring:
  application:
    name: js-consumer-financial
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true