server:
  port: 8024
spring:
  application:
    name: js-consumer-financial
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.153.204:7776/eureka/
  instance:
    hostname: 192.168.51.161
    prefer-ip-address: false
    instance-id: 192.168.51.161:8024
feign:
  hystrix:
    enabled: false
debug: true
logging:
  pattern:
    console: "%d - %msg%n"
