server:
  port: 8089
spring:
  application:
    name: js-consumer-register
eureka:
  client:
    service-url:
      defaultZone: http://39.105.7.229:6001/eureka/
  instance:
    prefer-ip-address: true
