server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.153.204:7776/eureka/
  instance:
    hostname: 192.168.51.161
    prefer-ip-address: false
    instance-id: 192.168.51.161:8084
spring:
  application:
    name: js-producer-fund
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.116.4:3306/bank?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: bank
    password: bank
  data:
    rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
    solr:
      host: http://47.95.116.4:8983/solr/bank/
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.jsproducerfund.pojo
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
redis:
  host: 127.0.0.1
  port: 6379
  database: 0
  jedis:
    pool:
      max-idle: 8 #最大空闲连接数
      min-idle: 0
      max-active: 8
      max-wait: 2000ms
timeout: 5000ms
#  data:
#    elasticsearch:
#        cluster-name: my-auction2
#        cluster-nodes: 47.100.246.114:9300
#        properties:
#        path:
#          logs: ./elasticsearch/logs
#          data: ./elasticsearch/data
#      repositories:
#        enabled: false
