server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@39.105.153.204:7776/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/jsyh?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19970121
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 3
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    #    验证数据库连接的查询语句（至少返回一条数据）
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  application:
    name: js-producer-creditcard
  profiles:
    active: dev
  zipkin: #追踪
    base-url: http://116.62.167.249:6601
  sleuth:
    sampler:
      percentage: 1.0
mybatis:
  mapper-locations: classpath:mapper/*.xml