server:
  port: 8082
spring:
  application:
    name: js-cosumer-fund
  rabbitmq:
    host: localhost
    port: 5672
    username: guset
    password: guest
eureka:
  client:
    register-with-eureka: true #将此项目注册到Eureka服务
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true