server:
  port: 8082
spring:
  application:
    name: js-cosumer-fund
  rabbitmq:
    host: localhost
    port: 5672
    username: guset
    password: guest
eureka:
  client:
    register-with-eureka: true #将此项目注册到Eureka服务
    service-url:
      defaultZone: http://root:123456@39.105.153.204:7776/eureka/
  instance:
    hostname: 192.168.51.161
    prefer-ip-address: false
    instance-id: 192.168.51.161:8082
feign:
  hystrix:
    enabled: true