server:
  port: 8082
spring:
  application:
    name: js-cosumer-fund
 rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
    virtual-host: /rabbit-1
    publisher-confirms: true
    publisher-returns: true
    listener:
        simple:
          prefetch: 1
eureka:
  client:
    register-with-eureka: true #将此项目注册到Eureka服务
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
feign:
  hystrix:
    enabled: true