server:
  port: 8023
spring:
  application:
    name: js-producer-financial
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.95.116.4:3306/bank?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: bank
    password: bank
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.jsproducerfinancial.pojo
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/